server:
  port: ":8090"

db:
  driver: "mysql"
  dsn: "root:root@tcp(127.0.0.1:3306)/temp?charset=utf8mb4&parseTime=True&loc=Local"

redis:
  enabled: true
  addr: "localhost:6379"
  password: "452836"
  db: 0

jwt:
  secret: "change-this-secret"
  expiration_hours: 72
